- hosts: all
  connection: local
#   user: "vagrant"
  gather_facts: yes
  become: yes
  vars:
    MAVEN_VERSION: "3.5.4"
    DEFAULT_MAVEN_DIR: "/opt/maven"
    GRADLE_VERSION: "4.3"
    DEFAULT_GRADLE_DIR: "/opt/gradle"
    JENKINS_USER: "jenkins"
    JENKINS_GROUP: "jenkins"
  roles:
    - { role: install-jenkins }