---
# tasks file for install-jenkins
- name: Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install azure gpg keys
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add azure repository
  yum_repository:
    name: azure-cli
    description: azure cli
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli

- name: Download jenkins repo config
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0755

- name: Install jenkins gpg keys
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Download jq
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    dest: /usr/bin/jq
    mode: 0755

- name: Install yum packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - wget
      - curl
      - unzip
      - python
      - git
      - bash
      - python2-pip
      - less
      - openssl
      - p7zip
      # - py-lxml
      - python2-pip
      - rsync
      - sshpass
      - sudo
      - subversion
      - vim
      - zip
      - bash
      # - ttf-dejavu
      - coreutils
      - openssh-clients
      # - build-dependencies
      - python-devel
      - libffi-devel
      - openssl-devel
      # - build-base
      # - ansible
      - azure-cli
      - java-1.8.0-openjdk.x86_64
      - jenkins

- name: create default directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ DEFAULT_MAVEN_DIR }}"
    - "{{ DEFAULT_GRADLE_DIR }}"
    - "{{ JENKINS_HOME }}"
    - "{{ JENKINS_HOME }}/tmp"
    - "/usr/share/jenkins"

- name: Download maven
  unarchive:
    src: "https://www-us.apache.org/dist/maven/maven-3/{{ MAVEN_VERSION }}/binaries/apache-maven-{{ MAVEN_VERSION }}-bin.tar.gz"
    dest: "{{ DEFAULT_MAVEN_DIR }}"
    remote_src: yes

- name: Download gradle
  unarchive:
    src: "https://services.gradle.org/distributions/gradle-{{ GRADLE_VERSION }}-bin.zip"
    dest: "{{ DEFAULT_GRADLE_DIR }}"
    remote_src: yes

# - name: Download jenkins
#   unarchive:
#     src: "https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/{{ JENKINS_VERSION }}/jenkins-war-{{ JENKINS_VERSION }}.war"
#     dest: "/usr/share/jenkins"
#     remote_src: yes

# - name: Add the group 'jenkins'
#   group:
#     name: "{{ JENKINS_GROUP }}"
#     gid: "{{ JENKINS_GUID }}"
#     state: present

# - name: Add the user 'jenkins'
#   user:
#     name: "{{ JENKINS_USER }}"
#     comment: user for Jenkins
#     uid: "{{ JENKINS_UID }}"
#     group: "{{ JENKINS_GROUP }}"
#     home: "{{ JENKINS_HOME }}"
#     state: present

- name: Change directories ownership
  file:
    path: "{{ item }}"
    owner: "{{ JENKINS_USER }}"
    group: "{{ JENKINS_GROUP }}"
  with_items:
    - "{{ JENKINS_HOME }}"
    - "/opt"
    # - "/usr/share/jenkins"
    - "/etc/ansible"

- name: Link maven, gradle and jenkins
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ DEFAULT_MAVEN_DIR }}/apache-maven-{{ MAVEN_VERSION }}/bin/mvn", dest: "/usr/bin/mvn" }
    - { src: "{{ DEFAULT_GRADLE_DIR }}/gradle-{{ GRADLE_VERSION }}/bin/gradle", dest: "/usr/bin/gradle" }
    # - { src: "/usr/share/jenkins/jenkins-war-{{ JENKINS_VERSION }}", dest: "/usr/share/jenkins/jenkins.war" }

- name: enable a jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
