---
# tasks file for install-jenkins
- name: Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install azure gpg keys
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add azure repository
  yum_repository:
    name: azure-cli
    description: azure cli
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli

- name: Download jq
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    dest: /usr/bin/jq
    mode: 0755

- name: Install yum packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - wget
      - curl
      - unzip
      - python
      - git
      - bash
      - python2-pip
      - less
      - openssl
      - p7zip
      # - py-lxml
      - python2-pip
      - rsync
      - sshpass
      - sudo
      - subversion
      - vim
      - zip
      - bash
      # - ttf-dejavu
      - coreutils
      - openssh-clients
      # - build-dependencies
      - python-devel
      - libffi-devel
      - openssl-devel
      # - build-base
      # - ansible
      - azure-cli
      - java-1.8.0-openjdk.x86_64

- name: create default directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "{{ DEFAULT_MAVEN_DIR }}"
    - "{{ DEFAULT_GRADLE_DIR }}"
    - "{{ JENKINS_HOME }}"

- name: Download maven
  unarchive:
    src: "https://www-us.apache.org/dist/maven/maven-3/{{ MAVEN_VERSION }}/binaries/apache-maven-{{ MAVEN_VERSION }}-bin.tar.gz"
    dest: "{{ DEFAULT_MAVEN_DIR }}"
    remote_src: yes

- name: Download gradle
  unarchive:
    src: "https://services.gradle.org/distributions/gradle-{{ GRADLE_VERSION }}-bin.zip"
    dest: "{{ DEFAULT_GRADLE_DIR }}"
    remote_src: yes

- name: Link maven and gradle
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ DEFAULT_MAVEN_DIR }}/apache-maven-{{ MAVEN_VERSION }}/bin/mvn", dest: "/usr/bin/mvn" }
    - { src: "{{ DEFAULT_GRADLE_DIR }}/gradle-{{ GRADLE_VERSION }}/bin/gradle", dest: "/usr/bin/gradle" }
